spring:
  datasource:
    url: jdbc:mysql://43.142.164.241:3306/mysql_app
    username: root
    password: robin_root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  transaction:
    rollback-on-commit-failure: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    openInView: false

springdoc:
  apiDocs:
    enabled: true
  swagger-ui:
    enabled: true

custom:
  sm4:
    key: chat_gpt_box